# Generated by Django 4.2.4 on 2023-09-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('site', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter_x', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('site', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter_x', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao_em_minutos', models.IntegerField()),
                ('data_disponibilizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('episodios', models.ManyToManyField(to='app.episodio')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao_em_minutos', models.IntegerField()),
                ('sinopse', models.CharField(max_length=200)),
                ('site_oficial', models.CharField(max_length=60)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais')),
                ('temporadas', models.ManyToManyField(to='app.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao_em_minutos', models.IntegerField()),
                ('sinopse', models.CharField(max_length=200)),
                ('site_oficial', models.CharField(max_length=60)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atores', models.ManyToManyField(to='app.ator')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais')),
            ],
        ),
        migrations.AddField(
            model_name='diretor',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
        migrations.AddField(
            model_name='ator',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
    ]
