# Generated by Django 4.2.4 on 2023-09-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(to='app.genero'),
        ),
    ]
