# Generated by Django 4.2.4 on 2023-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_filme_genero_filme_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.AddField(
            model_name='serie',
            name='genero',
            field=models.ManyToManyField(to='app.genero'),
        ),
    ]
