# Generated by Django 4.2.4 on 2023-09-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_serie_genero_serie_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='genero',
            new_name='generos',
        ),
    ]
